---
title: "Homework 2"
author: "Philip Kim"
date: "10/1/2021"
output: 
  github_document:
    toc: true
    toc_depth: 6
---

```{r, message = FALSE}
library(tidyverse)
library(readxl)
```

# Problem 1

## Read/Clean Mr. Trash Wheel Dataset

```{r}
trashwheel_df = read_excel(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = 1,
  range = "A2:N406") %>% 
  janitor::clean_names() %>% 
  drop_na(dumpster) %>% 
  mutate(sports_balls = round(sports_balls, digits = 0))
```

## Clean Precipitation Data for 2018 and 2019

### Precipitation Data for 2018

```{r}
precipitation_2018 = read_excel(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = 5,
  skip = 1) %>%
  drop_na(Month) %>% 
  mutate(year = "2018")
```


### Precipitation Data for 2019

```{r}
precipitation_2019 = read_excel(
  "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = 4,
  skip = 1) %>% 
  drop_na() %>% 
  mutate(year = "2019")
```


### Combining Precipitation Data

```{r}
precipitation_combined = 
  bind_rows(precipitation_2018, precipitation_2019) %>% 
  janitor::clean_names() %>% 
  relocate(year) %>% 
  rename(total_in = total) %>% 
  mutate(month = month.name[month])
```


## Data Observations Paragraph



# Problem 2

## Clean pols-month data 

```{r}
politician_df = read.csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(mon, c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    month = month.name[month],
    president = case_when(prez_gop == "1" ~ "gop", prez_dem == "1" ~ "dem")) %>%  
  select(-prez_gop, -prez_dem, -day)
```


## Clean snp data

```{r}
snp_df = read.csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  separate(date, c("month", "day", "year"), convert = TRUE) %>% 
  mutate(
    month = factor(month.name[month], levels = month.name),
    year = if_else(year > 15, year + 1900, year + 2000)) %>% 
  arrange(year, month) %>% 
  select(year, month, close)
```


## Clean unemployment data

```{r}
unemployment_df = read.csv("./data/fivethirtyeight_datasets/unemployment.csv")

unemployment_tidy_df = 
  pivot_longer(
    unemployment_df,
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment_perc") %>% 
  janitor::clean_names() %>% 
  mutate(month = match(month, month.abb),
         month = month.name[month])
```


## Join Datasets

```{r}
snp_pols_df = 
  left_join(politician_df, snp_df, by = c("year", "month"))

snp_pols_unemp_df =
  left_join(snp_pols_df, unemployment_tidy_df, by = c("year", "month"))
```

## Dataset Description



# Problem 3

```{r}

```

